### ISSUE TITLE
请问可以给一个在ubuntu无网络环境下的portal安装包吗？开箱即用的。感谢

### ISSUE THREAD

**Issue by Muz1379** [ayamir/nvimdots#1063]
### Feature description

工作环境需要在ubuntu命令行下写代码，但是没有网络。

**Comment by CharlesChiuGit** [comment]
i think u can and should pack up yourself.

**Comment by ayamir** [comment]
We won't provide any portable installer for `nvimdots` because it just an organization of config files about plugins and their configs and requires many system-wide dependencies to work. You can do it by yourself according to following steps.
1. Download the require dependencies like `deb` or executable binaries matching your Ubuntu version first.
2. Create archives of `~/.local/share/nvim` and `~/.config/nvim` and upload them to your Ubuntu machine.
3. Decompress them to the corresponding directory.

**Comment by ayamir** [comment]
More info may helps:
https://www.reddit.com/r/neovim/comments/lncqxl/remote_neovim_like_vscode/
https://github.com/jbyuki/instant.nvim
