### ISSUE TITLE
Add `harlequin` as a database management tool

### ISSUE THREAD

**Issue by Rehtt** [ayamir/nvimdots#1163]
### Feature description

使用 [harlequin](https://github.com/tconbeer/harlequin)作为数据库管理工具，就像git管理使用`lazygit`一样

**Comment by CharlesChiuGit** [comment]
i'm not sure if it's necessary to include this feature in the repo, since not all needs to work with databases. 

maybe it would suit better in your own fork?

**Comment by ayamir** [comment]
`lazygit` and `harlequin` both are external tools instead of `nvim` plugin. They don't have direct relationship with `nvim` and you can use them in terminal directly. What we can do is only adding a keymap for it like `<leader>gg` for `lazygit` in `toggleterm`.
As @CharlesChiuGit said, not all need to work with databases. You can set it on your own.
