### ISSUE TITLE
<A->相关的快捷键没有反应

### ISSUE THREAD

**Issue by AspieterPan** [ayamir/nvimdots#344]
### Neovim version

NVIM v0.8.1 Build type: Release

### Operating system/version

macOS Ventura 13.0.1 (22A400)

### Terminal name/version

iTerm2 Build 3.4.18

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

使用 option 键相关的快捷键，没有任何反应 (使用的是MacBook Pro)
contrl 和 shift 相关的快捷键都可以正常使用

1. 测试1: 具体使用的按键是 option + j/k 的切换buffer没有生效
2. 测试2：在配置文件中，将<C-h>按键改为<A-h>或<M-h>后，按下 option + h 没有反应，按下 <C+w> + h 成功切换窗口

### Expected behavior

能够正常使用 option 键相关的快捷键

**Comment by Jint-lzxy** [comment]
By default, the Alt-key doesn't work in any MacOS Terminal since all `alt`-related keys are mapped to the corresponding **real character generated**. For example:
```console
<A-g> --> ©
<A-S-p>(upper case `p`) --> ∏ 
```
There are two solutions, you may choose the one that suits you best 👍 

1. Map the `Alt` key to the corresponding output symbol _(e.g., `<A-g> --> ©`)_, you may refer to [my config](https://github.com/Jint-lzxy/nvimconfig/blob/6aaade0355d77739aefa2b11b076a90e61e63fde/lua/keymap/init.lua#L10) for more information. Do note that you need to change two files: `lua/keymap/init.lua` and `lua/core/mapping.lua`.
2. Looks like you are using `iTerm2`. You may Open "Preferences" (<kbd>⌘,</kbd>) -> `Profiles` _(select your current profile)_ -> `Keys` -> `General` tab, and set the `Left/Right Option key` to `Esc+`. As shown: _(Note: In this mode, the modified left/right option key **can no longer be used to input symbols in the terminal**)_
<img width="1128" alt="iterm-opt" src="https://user-images.githubusercontent.com/50296129/205058533-d0a35970-3b86-45c4-9abd-d634a5b4e90c.png">

**Comment by AspieterPan** [comment]
我用了修改 iterm profile 的方法，现在可以正常使用了
非常感谢！

**Comment by ayamir** [comment]
For `kitty` user, set `macos_option_as_alt yes` in `~/.config/kitty/kitty.conf`.
