### ISSUE TITLE
第一次进入vim打开文件的时候只显示了一半,退出以后再打开文件显示完整，但是再退出的时候就退出到命令行界面了

### ISSUE THREAD

**Issue by Kotodian** [ayamir/nvimdots#390]
<img width="1885" alt="image" src="https://user-images.githubusercontent.com/22030659/210028830-250d1841-1fc0-4e7f-bda5-f799edc48b17.png">

**Comment by CharlesChiuGit** [comment]
Can you try re-clone this repo and see if that helps?

**Comment by Kotodian** [comment]
> Can you try re-clone this repo and see if that helps?

<img width="251" alt="image" src="https://user-images.githubusercontent.com/22030659/210031116-61f1749c-2956-42db-b484-2fcb3da5eeb3.png">
我已经是重新下了好几次了，没有上次的报错了，但是还是有这个问题

**Comment by ayamir** [comment]
我看不懂你在说什么，能不能按照模板的要求提issue？你这种issue很浪费人时间。

**Comment by Jint-lzxy** [comment]
@Kotodian Can you help fill in the [issue form](https://github.com/ayamir/nvimdots/issues/new?assignees=&labels=bug&template=bug_report.yml)? This issue provides too little information _(for example, how you opened the file? Through nvim-tree/treesitter/other approaches?)_, we can't _infer_ the problem from a simple description. Instead, we need steps that can help us **reproduce** this problem so that we can help you with the issue.

Gonna close it now, sorry for the inconvenience.
