### ISSUE TITLE
[telescope] Support project level live grep

### ISSUE THREAD

**Issue by kevin1sMe** [ayamir/nvimdots#413]
### Feature description

目前内置的插件搜索有个问题，即基于当前相对路径的搜索。如果已经进入某个目录，那么搜索只会在对应目录下而不会往上到.git根目录。希望支持如文件搜索的<leader>+`f`+`g`类似的在整个工程搜索目标字符串。

**Comment by Jint-lzxy** [comment]
@kevin1sMe You can browse known projects _(which will be automatically detected in most cases by [pattern matching](https://github.com/ahmedkhalf/project.nvim#pattern-matching))_ using `<leader>fp`, and then use keybindings to perform different types of searches when a project is selected. You can find all supported query categories [here](https://github.com/ahmedkhalf/project.nvim#telescope-mappings). Your requirements can be met by pressing `w` after selecting the target item.

For more detailed plugin information, please refer to: [ahmedkhalf/project.nvim](https://github.com/ahmedkhalf/project.nvim).

**Comment by kevin1sMe** [comment]
谢谢解答，确实可以。
不过需要先打开project再切换到live grep。对于查找行为还是比较常用的，是否可以定制一个快捷键。对于这种情况下的快捷键不懂如何设置，还请指导，再次感谢！

**Comment by kevin1sMe** [comment]
当前配置中的这个：
```
["n|<Leader>fw"] = map_cu("Telescope live_grep"):with_noremap():with_silent(),
```
是不支持我所说的项目级别搜索，它是当前目录搜索的结果。而基于telescope project.nvim插件的`search_in_project_files`是满足需求的，是否可以切换到这种级别或多提供一个选择。

**Comment by Jint-lzxy** [comment]
> 不过需要先打开project再切换到live grep。对于查找行为还是比较常用的，是否可以定制一个快捷键。

FWIW this does not require additional configuration. After you select the current project, it will always appear at the top of the list. Only `<leader>fp<C-s>` is needed to complete the feature you request.

**Comment by Jint-lzxy** [comment]
> 是不支持我所说的项目级别搜索，它是当前目录搜索的结果。而基于telescope project.nvim插件的`search_in_project_files`是满足需求的，是否可以切换到这种级别或多提供一个选择。

Emm that's true, it is possible to save a few unnecessary keystrokes. I will start to implement this feature later, there are some corner cases that must be considered. Unfortunately, `telescope` does not have built-in support for this feature.

**Comment by Jint-lzxy** [comment]
I believe this requires a lot of work _(we need the assistance of `plenary.nvim` and many checks are required to determine the root directory)_, and there are already some existing plugins that could provide this feature. Besides, FWIW it is unrealistic to implement a feature that requires a lot of design just to save a few keystrokes. What's your opinion?
Or is there a better way to implement this feature?

cc @ayamir @CharlesChiuGit

**Comment by ayamir** [comment]
> 目前内置的插件搜索有个问题，即基于当前相对路径的搜索。如果已经进入某个目录，那么搜索只会在对应目录下而不会往上到.git根目录。

live_grep根据的是当前工作目录，并不是你所说的当前相对路径。当前工作目录本身就是由project.nvim这一插件所确定的，其工作原理是lsp和模式匹配。你只需要将能定义你工程根目录的文件以正则表达式的形式加入到project.nvim的模式匹配的候选项中，就可以将当前工作目录设定为你所说的工程目录。

https://github.com/ayamir/nvimdots/blob/0e47a512827395781daea8c62efa6297c685b658/lua/modules/tools/config.lua#L112

https://github.com/ahmedkhalf/project.nvim#pattern-matching

**Comment by CharlesChiuGit** [comment]
My personal config is set to fuzzy find all the files and strings in one project, it's played nice most of the time( and my projects are not those huge mono repo). 
However, it has one downside, this settings will not show cwd correctly, it will fix to your project root.

**Comment by CharlesChiuGit** [comment]
@ayamir I notice sometimes `live_grep` will change it's `cwd` if you call `live_grep` twice in a row. I'm not sure if that's intended or a bug.
1. First time call `live_grep` or `find_files`, it will fuzzy find strings and files of correct `cwd`, for example, `lua/modules/ui`.
2. Do nothing and quite telescope.
3. Call `live_grep` or `find_files` again, now the fuzzy finder will set the `cwd` to project root, for example, `~/.config/nvim`.

It might due to the order of lazy loading I guess, but after a few tests, I still can't reproduce my personal configs to this repo, or vice versa.

**Comment by CharlesChiuGit** [comment]
@ayamir @Jint-lzxy I notice sometimes `live_grep` will change it's `cwd` if you call `live_grep` twice in a row. I'm not sure if that's intended or a bug.
1. First time call `live_grep` or `find_files`, it will fuzzy find strings and files of correct `cwd`, for example, `lua/modules/ui`.
2. Do nothing and quite telescope.
3. Call `live_grep` or `find_files` again, now the fuzzy finder will set the `cwd` to project root, for example, `~/.config/nvim`.

It might due to the order of lazy loading I guess, but after a few tests, I still can't reproduce my personal configs to this repo, or vice versa.

**Comment by Jint-lzxy** [comment]
@kevin1sMe Looks like you are using your [own fork](https://github.com/kevin1sMe/nvimdots). I suspect you haven't synchronized your main branch in time. During this period, we supported `nvim` 0.8 and made several plugin adjustments. This change was introduced in https://github.com/ayamir/nvimdots/commit/eccded38bd23ce7724032cc76941a8aff81da364 and https://github.com/ayamir/nvimdots/commit/71ae7c6f789b223cdd08f116bbe50f82216b9af3. You can still complete the search because [telescope-project.nvim](https://github.com/nvim-telescope/telescope-project.nvim) turns out to have the same key binding. However, it has been formally replaced with [project.nvim](https://github.com/ahmedkhalf/project.nvim) in https://github.com/ayamir/nvimdots/commit/71ae7c6f789b223cdd08f116bbe50f82216b9af3.

cc @ayamir

**Comment by Jint-lzxy** [comment]
> I notice sometimes `live_grep` will change it's `cwd` if you call `live_grep` twice in a row. I'm not sure if that's intended or a bug.

It's _indeed_ intended. This is exactly how [project.nvim](https://github.com/ahmedkhalf/project.nvim#-features) works. In fact, the change has already occurred on your first entry.

https://github.com/ayamir/nvimdots/blob/45dadcf923498bc2f093aad00f8f3753c8996c98/lua/modules/tools/config.lua#L116-L117

You can set `silent_chdir` to `false` to watch the changes.

**Comment by CharlesChiuGit** [comment]
> You can set `silent_chdir` to `false` to watch the changes.

Seems reasonable, but the behavior of my fork to this repo doesn't seem to change after I set `silent_chdir` to false and `PackerCompile` it. I'll dig in a bit deeper to check if there is some setting I missed.

**Comment by Jint-lzxy** [comment]
No, the behavior will never change, because this is the original design pattern. When you set `silent_chdir` to `false, it will only notify you when it switches directories.

**Comment by CharlesChiuGit** [comment]
my fault! I saw the message now.

**Comment by CharlesChiuGit** [comment]
@kevin1sMe I might have a workaround for u. 
u can set some keymaps like
```lua
local keymap = vim.api.nvim_set_keymap
local opts = { noremap = true, silent = true, nowait = true }
keymap("n", "<leader>pf", "<cmd>ProjectRoot<cr><cmd>Telescope find_files<cr>", opts)
keymap("n", "<leader>pw", "<cmd>ProjectRoot<cr><cmd>lua require('telescope').extensions.live_grep_args.live_grep_args{}<cr>", opts)
```

But notice, once u change `cmd` to project root, u can't change it back in current nvim instance.

**Comment by Jint-lzxy** [comment]
@CharlesChiuGit I believe this problem is due to https://github.com/ayamir/nvimdots/issues/413#issuecomment-1378117009. Because this problem cannot be reproduced using the default configuration, and the author has claimed that there is a `.git` folder in his working directory.

After executing this keybinding, one would probably get:
```console
E492: Not an editor command: ProjectRoot
```

**Comment by CharlesChiuGit** [comment]
> @CharlesChiuGit I believe this problem is due to https://github.com/ayamir/nvimdots/issues/413#issuecomment-1378117009. Because this issue cannot be reproduced using the default configuration, and the author has claimed that there is a `.git` folder in his working directory.
> 
> 
> 
> After executing this keybinding, one would probably get:
> 
> ```console
> 
> E492: Not an editor command: ProjectRoot
> 
> ```

That shouldn't be, since it's the command from project.nvim, are u sure it's loaded?

**Comment by Jint-lzxy** [comment]
No, I mentioned in https://github.com/ayamir/nvimdots/issues/413#issuecomment-1378117009 that the author probably didn't sync his branch and the plugin still [telescope-project.nvim](https://github.com/nvim-telescope/telescope-project.nvim), **not** [project.nvim](https://github.com/ahmedkhalf/project.nvim).

**Comment by CharlesChiuGit** [comment]
ah, got it. thanks for clarifying that.

**Comment by kevin1sMe** [comment]
It works after update to the latest `master`. Thank you all.👍
