### ISSUE TITLE
大量文本复制的时候，很容易假死，卡死

### ISSUE THREAD

**Issue by nevertoday** [ayamir/nvimdots#489]
### Feature description

我macmini m2 上，配置好了，然后复制大量文本，cmd+c之后，进入具体问题， 打算进入cmd+v流程，但是就会多次卡死：
https://raw.githubusercontent.com/SlRvb/Obsidian--ITS-Theme/main/Snippets/S%20-%20Checkboxes.css
这个页面的内容是我复制的内容，但是我一旦粘贴进入，就很容易假死，
过程中，我可以看到nvim界面中，右下角出现的pasting 状态进度条，但最终还是假死，整个tab 编辑页面，不能用，
我也很是确定我的系统和软件还有终端环境是好的。

hope u reply ,and thks!

**Comment by ayamir** [comment]
Try `p` in normal mode instead of `command+v`.

**Comment by nevertoday** [comment]
thanks , 'p' works so good !
and how can I upgrade nvimdot to newest with commands?

**Comment by ayamir** [comment]
Just `git pull origin main` at `~/.config/nvim` if you don't your custom configurations. Check release note of version 2.0.0 [here](https://github.com/ayamir/nvimdots/releases/tag/v2.0.0) otherwise.

**Comment by nevertoday** [comment]
thanks

**Comment by Jint-lzxy** [comment]
@nevertoday Just a bit of background knowledge here _(if you would like to know more)_:

If you use `<C-v>` to paste some texts, `vim` will not treat this as an instruction _(if you use `q` to record what you did into a register, `<C-v>` will be ignored)_. Instead, `vim` will think that you are entering texts normally **one by one**. It will run all autocmds and perform most checks _(such as adjusting text indentation)_ in the background. Those keymaps exist only to help users migrate more seamlessly to `vim`, but it is not intended to let users use them on a large scale. So if possible, try to use native commands instead of those "compatible commands" for better performance.

**Comment by Jint-lzxy** [comment]
@nevertoday Just a bit of background here _(if you would like to know more)_:

If you use `<C-v>` to paste some texts, `vim` will not treat this as an instruction _(if you use `q` to record what you did into a register, `<C-v>` will be ignored)_. Instead, `vim` will think that you are entering texts normally **one by one**. It will run all autocmds and perform most checks _(such as adjusting text indentation)_ in the background. Those keymaps exist only to help users migrate more seamlessly to `vim`, but it is not intended to let users use them on a large scale. So if possible, try to use native commands instead of those "compatible commands" for better performance.

**Comment by CharlesChiuGit** [comment]
Side note: I think this kind of educational infos are really valuable. @ayamir Would u mind me to create a wiki page to list out all gd issues?

**Comment by ayamir** [comment]
> Would u mind me to create a wiki page to list out all gd issues? Since github issue can only pin 3 issues at most.

Wonderful idea. I'm glad to see it! 👍
