### ISSUE TITLE
CTRL-U doesn't work in insert mode

### ISSUE THREAD

**Issue by asaning** [ayamir/nvimdots#616]
### Feature description

when i want to rollback to the last input,it just returns the input throught my keyborad, the part of suggestions is keep.
it doesn't help me.

**Comment by Jint-lzxy** [comment]
Can you help fill in the [issue form](https://github.com/ayamir/nvimdots/issues/new?assignees=&labels=bug&template=bug_report.yml)? This issue provides too little information, and we can't _infer_ the problem from a simple description. Instead, we need **steps** that could **reproduce** this problem (describe _what you have done_ in an ordered list) so that we can help you with the issue.

Gonna close it now, sorry for the inconvenience.

***

As per requirements for opening an issue:
> Issues without any information will be closed directly.

**Comment by asaning** [comment]
sorry, please let me gives a detailed describe, let me take a example.

![image](https://user-images.githubusercontent.com/99789353/230244705-49fffa77-cfcf-41eb-8eb0-c537d6e89e40.png)

in the picture, i just wirte the `for` and then the other code is completed by `lsp`, and then when i want to use the the `ctrl-u` the remove the last input, it doesn't remove the entry `for` statement.

**Comment by Jint-lzxy** [comment]
You _misunderstood_ the usage of this command:
```console
						*i_CTRL-U*
CTRL-U		Delete all entered characters before the cursor in the current
		line.  If there are no newly entered characters and
		'backspace' is not empty, delete all characters before the
		cursor in the current line.
		If C-indenting is enabled the indent will be adjusted if the
		line becomes blank.
		See |i_backspacing| about joining lines.
```
**Instead, you should use `<C-o>u`:**
```console
CTRL-O		execute one command, return to Insert mode   *i_CTRL-O*
```

**Comment by asaning** [comment]
so, i can use the `ctrl-o` to normal mode,and then use `u` to rollback.

**Comment by Jint-lzxy** [comment]
Yep, as `nvim` provides a _very limited_ number of commands for maintaining the undo list.

But you can bind a custom mapping to this combination, e.g:
```lua
["i|<C-l>"] = map_cmd("<C-\\><C-o>u"):with_noremap():with_silent(),
```

See also:
```console
CTRL-\ CTRL-O	like CTRL-O but don't move the cursor	     *i_CTRL-\_CTRL-O*
```
