### ISSUE TITLE
New icons do not render properly in tmux

### ISSUE THREAD

**Issue by ayamir** [ayamir/nvimdots#725]
### Discussed in https://github.com/ayamir/nvimdots/discussions/720

<div type='discussions-op-text'>

<sup>Originally posted by **AngelontheRoad** May  7, 2023</sup>
I just merged #447 and updated all plugins. I tried to use the new nerd font with `Mono` and `Propo` and everything works perfectly without `tmux`. But inside `tmux` I found that icons were not rendered properly.

inside `tmux`:
![quicker_cf16e16a-d84d-40f0-a9a6-6af9aa1cebec.png](https://s2.loli.net/2023/05/07/omJXCP4kntrKSzx.png)

outside `tmux` is OK:
![quicker_58aeb3d9-cf82-4be2-a81f-4f79e6815336.png](https://s2.loli.net/2023/05/07/N4pc6OzRgGM2i8Q.png)

I found a [reddit post](https://www.reddit.com/r/tmux/comments/135ggtb/nerd_font_not_rendered_perfectly_in_tmux/) that has a similar problem, but no solution works for me.

By the way, I noticed that icons baseline is not a straight line (marked above).😥

Is there any help? Thanks
</div>

**Comment by ayamir** [comment]
Occurs on `zellij` too. Maybe have to do with environment variables.

**Comment by ayamir** [comment]
Have no idea about it now.

**Comment by AngelontheRoad** [comment]
According to the issue posts in [wezterm](https://github.com/wez/wezterm/issues/3704) and [tmux](https://github.com/tmux/tmux/issues/3566), the render problem may caused by [ConPTY](https://github.com/wez/wezterm/issues/3704#issuecomment-1542533272) which used only in Windows system.  I don't know if this is a problem in a real linux box.

As mentioned in the post, `ssh` is a feasible way to bypass ConPTY. B/C alacritty is not a multiplexier, I tried in wezterm and it rendered OK.

![quicker_af4efdba-2d6a-4381-b546-772500ccbc7d.png](https://s2.loli.net/2023/05/20/NWaRqLInz9pcl3G.png)

### Steps:
1. set `systemd=true` under `/etc/wsl.conf` `[boot]`
2. download `openssh` in wsl2.
3. shutdown wsl2 by `wsl --shutdown`
4. uncomment or add below in `/etc/ssh/sshd_config` (Port number larger than 1000 is recommended)
```
Port 2222
ListenAddress 0.0.0.0  
PasswordAuthentication yes
PubkeyAuthentication yes
PasswordAuthentication yes
AcceptEnv LANG LC_*
```
5. if using `Ubuntu-22.*`,  set `ListenStream=2222` in `/lib/systemd/system/ssh.socket` 
6. restart `ssh` service by `sudo systemctl restart ssh`
7. get wsl2 IP address by `wsl hostname -I`
8. establish `ssh` connection by `wezterm ssh username@ip:2222`. If ssh key exists, use `wezterm ssh -oIndentityFile='~/.ssh/yoursshkey' username@ip:2222`. But I recommend to set `ssh_domains` in wezterm configuration file.

### Summary
In general, this solution may be effective for solving render problems that exist only in wsl (such as undercurl) unless microsoft updates ConPTY. In my short using experience, the only bug is that spawning a new `cmd` or `powershell` tab in ssh window will crash wezterm. I don't know how it works in other terminals. IMHO, **wsl users who rely on `tmux` but hate trivial settings, use wezterm straightly is a better choice**

**Comment by ayamir** [comment]
> According to the issue posts in https://github.com/wez/wezterm/issues/3704 and https://github.com/tmux/tmux/issues/3566, the render problem may caused by https://github.com/wez/wezterm/issues/3704#issuecomment-1542533272 which used only in Windows system.

Indeed, it doesn't occurs on my gentoo linux.
