### ISSUE TITLE
can't toggle the recently suggestion

### ISSUE THREAD

**Issue by asaning** [ayamir/nvimdots#744]
### Feature description

please see the below picture.

1, the first time i write the `match` keyword and then select the snippet style
2, the second time i write the `match` keyword, the snippet style isn't the first one in the waiting suggestion list

by the way, the order of the suggestion seems sort by name exactly, how can i fix it.

![image](https://github.com/ayamir/nvimdots/assets/99789353/2f1ff566-782d-46bd-9384-128c9108c8b7)

**Comment by Jint-lzxy** [comment]
> by the way, the order of the suggestion seems sort by name exactly

Hmm _not really_:
https://github.com/ayamir/nvimdots/blob/42e816b9d465b69110de639b1afd94b3ce1fa5c8/lua/modules/configs/completion/cmp.lua#L86-L101

In fact your issue is not related to this configuration - just b/c `cmp` will not cache your previous selections. Of course, you can always write custom comparators to achieve this.

**Comment by ayamir** [comment]
> the order of the suggestion seems sort by name exactly, how can i fix it.

comment this line:
https://github.com/ayamir/nvimdots/blob/42e816b9d465b69110de639b1afd94b3ce1fa5c8/lua/modules/configs/completion/cmp.lua#L97

**Comment by Jint-lzxy** [comment]
Yep I'm adjusting this list based upon the recently merged folke's PR 😄 FWIW the default isn't arranged in the best possible way - sometimes less commonly used entries might even precede LSP suggestions.
