### ISSUE TITLE
cannot understand keybinding

### ISSUE THREAD

**Issue by LysanderT** [ayamir/nvimdots#811]
for example, I want to use this hotkey:
```
toggle floating terminal | N | <A-d>
```
and i try ```<space> + letter <A> + letter <d>```
but when i press ```<A>```, it always output "E21 不能修改：因为选项‘modifiable‘是关的"

I also guess `A` represent `Alt`. Since `option` is the macOS version of `Alt`, so I try pressing `option`. But still not work

**Comment by LysanderT** [comment]
I guess `A` represent `Alt`. Since `option` is the macOS version of 'Alt', so I tried pressing 'option'. But still not work

**Comment by LysanderT** [comment]
And when I want to use `ga` in
```
show code action | N | ga
```
but it just pop `method textDocument/codeAction is not supported by any of the servers registered for the current buffer`

I installed all the prerequisite packages and i don't know why it cannot work

**Comment by fecet** [comment]
method textDocument/codeAction is not supported by any of the servers registered for the current buffer means your lsp doesn't support code action, so you can't use `ga` in this file.

<A-d> is alt+d in my setup, you cannot trigger this?

**Comment by LysanderT** [comment]
Is lsp a plugin instead of a built-in feature? i'm new to neovim and just install your config. Isn't it enough to just install the prerequisite you required in the wiki and run the shell script to use neovim?

and yes, `alt+d` cannot work. I check my system hotkey setup to see whether there exists a conflict but find nothing.

**Comment by ayamir** [comment]
> for example, I want to use this hotkey:
> 
> ```
> toggle floating terminal | N | <A-d>
> ```
> 
> and i try `<space> + letter <A> + letter <d>` but when i press `<A>`, it always output "E21 不能修改：因为选项‘modifiable‘是关的"
> 
> I also guess `A` represent `Alt`. Since `option` is the macOS version of `Alt`, so I try pressing `option`. But still not work

https://github.com/ayamir/nvimdots/issues/344#issuecomment-1333725188

**Comment by ayamir** [comment]
> Is lsp a plugin instead of a built-in feature?

Yes. We have configured some common lsp servers to make it work out of box.

> `method textDocument/codeAction is not supported by any of the servers registered for the current buffer`

Different lsp servers have different levels of support. For example, [bashls](https://github.com/bash-lsp/bash-language-server) doesn't support lsp rename and find reference by scope.

**Comment by Jint-lzxy** [comment]
FYI: [intro.txt#key-notation](https://neovim.io/doc/user/intro.html#key-notation). An editor (strictly speaking, _a service provider_) semantically parses your code in order to understand them and could provide support for advanced features such as code actions. Most editors exchange "messages" with the server (or the executable installed on your host machine) through [Language Server Protocol (LSP)](https://microsoft.github.io/language-server-protocol/), and the capabilities that the server has are _closely_ related to the implementation of its Abstract Syntax Tree (AST). Neovim [implements the _protocol_ internally](https://neovim.io/doc/user/lsp.html) (or builtin), but how it's utilized depends on how the user configures that (e.g., [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) provides quickstart configs for Nvim LSP).

One significant difference from say, VSCode is that the vsix extension you install completes all those configuration behind the scene, but NeoVim does not - in other words, VSCode sacrifices extensibility in exchange for a completely out-of-box experience; NeoVim, on the other hand, focuses more on "grabbing what you need", which provides huge possibilities for custom configs.

**Comment by LysanderT** [comment]
> Different lsp servers have different levels of support. For example, [bashls](https://github.com/bash-lsp/bash-language-server) doesn't support lsp rename and find reference by scope.
so i need to replace my lsp server with another one right?

**Comment by ayamir** [comment]
> so i need to replace my lsp server with another one right?

if you can find a better one :)

**Comment by LysanderT** [comment]
> @LysanderT FYI: [intro.txt#key-notation](https://neovim.io/doc/user/intro.html#key-notation). An editor (strictly speaking, _a service provider_) semantically parses your code in order to understand them and could provide support for advanced features such as code actions. Most editors exchange "messages" with the server (or the executable installed on your host machine) through [Language Server Protocol (LSP)](https://microsoft.github.io/language-server-protocol/), and the capabilities that the server has are _closely_ related to the implementation of its Abstract Syntax Tree (AST). Neovim [implements the _protocol_ internally](https://neovim.io/doc/user/lsp.html) (or builtin), but how it's utilized depends on how the user configures that (e.g., [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) provides quickstart configs for Nvim LSP).

thanks for giving the explanation but i'm still confused. is it to say the shell script in the repo won't help configure lsp and i need to configure it by myself?

**Comment by LysanderT** [comment]
> if you can find a better replacement :)

oh i see. thank you for your kindness :)

**Comment by Jint-lzxy** [comment]
> is it to say the shell script in the repo won't help configure lsp and i need to configure it by myself?

Ys as @CharlesChiuGit said to use a server, you need the server itself _(the executable)_ **and** the correct protocol setups so that your server can start to exchange information with Neovim. We setup those servers via [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig).

Details on how to setup your servers: [Wiki: Usage#modify-lsps-linters-and-formatters](https://github.com/ayamir/nvimdots/wiki/Usage#modify-lsps-linters-and-formatters).

**Comment by LysanderT** [comment]
thank you guys, what you said helped me a lot :)
