### ISSUE TITLE
'Microsoft.PowerShell.Archive' could not be loaded

### ISSUE THREAD

**Issue by taynpg** [ayamir/nvimdots#854]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

Windows 10 Pro 22H2

### Terminal name/version

Windows Terminal 1.17.11461.0

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

Use :MasonInstall clangd module not loaded，but it exist.

![image](https://github.com/ayamir/nvimdots/assets/59216127/fb82fe39-f240-4d64-8d0a-213a516d0688)

### Expected behavior

Use :MasonInstall clangd module not loaded，but it exist.

![image](https://github.com/ayamir/nvimdots/assets/59216127/fb82fe39-f240-4d64-8d0a-213a516d0688)

**Comment by ayamir** [comment]
Can you provide the full log content here?

**Comment by taynpg** [comment]
I'm sorry to have cleaned up my environment due to an attempted repair

**Comment by taynpg** [comment]
Okay, I'll go back and try it tonight.

**Comment by Jint-lzxy** [comment]
> After I cleaned up my environment and replaced the installer choco with scoop, everything became OK, not sure why.

@taynpg A common cause of this issue is only the stub (or receipt) of this module exists on ur file system. Many factors, e.g., the backup mechanism of `MS OneDrive` could lead to this issue. u can think of this as a broken symlink.

When u change ur package manager, the installer probably recognizes this issue and restores the original copy for u. However, Mason's processing mechanism is rather simple and doesn't check for this.
