### ISSUE TITLE
Nvim run log

### ISSUE THREAD

**Issue by Lilihx** [ayamir/nvimdots#938]
### Feature description

Sometimes Nvim crashed for some reason. How can I debug that and find error log ?
Help

**Comment by Lilihx** [comment]
By the way, I find some error caused by the lack of some command tools.
Eg, the "word find in project" of  telescope is invalid in my nvim.  Actually, the reason is that I didnot install ripgrep which is needed for telescope plugin.
Can we add these to install.sh ?

**Comment by Jint-lzxy** [comment]
> Sometimes Nvim crashed for some reason. How can I debug that and find error log ?

IMO the first step is to provide a minimum _repro_ for this crash, since it's pretty difficult (for us) to find the root cause of ur issue without a reliable repro. It would be even better to also include relevant information about the crash (e.g., symbolized crash logs, core dumps, stack backtraces, etc.). `Neovim`'s runtime logs are rarely used - u don't need that to [file a bug report](https://github.com/ayamir/nvimdots/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml).

> By the way, I find some error caused by the lack of some command tools... Actually, the reason is that I didnot install ripgrep which is needed for telescope plugin.

Did u take a look at [Wiki:Prerequisites](https://github.com/ayamir/nvimdots/wiki/Prerequisites#required-packages-installation-for-archlinux)? There's a list dependencies required for \*nix users.

> Can we add these to install.sh ?

The main reason blocking us from implementing automatic dependency installation (like the Windows one) is that we have no plan to support each and every package managers for whatever distributions users would use. If we do start implementing this, at the end of the day the script will surely become extremely buggy and difficult to maintain. Feel free to open a PR if u think there's a better way to handle this.

**Comment by ayamir** [comment]
> Can we add these to install.sh ?

No way cause there are too many distros and we can't maintain it.

**Comment by fecet** [comment]
What's your platform? I have a crossplatform (unix only, I guess) [setup](https://github.com/SUSTech-data/cocker/blob/master/cocker/environments/poor.yml) for that

**Comment by CharlesChiuGit** [comment]
u can also reference my unix-only setup, if u can understand lol: https://github.com/CharlesChiuGit/dotfiles/tree/main/install_scripts
