### ISSUE TITLE
Special symbols in nvim that cannot be successfully displayed

### ISSUE THREAD

**Issue by trunliu** [ayamir/nvimdots#940]
### Feature description

I am confused about the meaning of these special symbols such as `F07B F07C E620` as the following image, 
and how to fix them ?

### Additional information

![image](https://github.com/ayamir/nvimdots/assets/55086037/38c20086-c96a-4b4b-b7ee-4bd639ef7fe5)

**Comment by CharlesChiuGit** [comment]
just apply nerdfonts to your terminal

**Comment by Jint-lzxy** [comment]
These are bare Unicode codepoints and u need to install a [patched font](https://www.nerdfonts.com/font-downloads) in order to have those icons rendered correctly. Did u follow [Wiki:Prerequisites](https://github.com/ayamir/nvimdots/wiki/Prerequisites#required-packages-installation-for-archlinux) before u start?

**Comment by trunliu** [comment]
> just apply nerdfonts to your terminal

Thx! I have done as following
```bash
curl -OL https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip
unzip JetBrainsMono.zip
mv * /usr/share/fonts
reboot
```
