### ISSUE TITLE
Lspsaga missing "current identifier" highlight

### ISSUE THREAD

**Issue by Robin329** [ayamir/nvimdots#948]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

 Linux ubuntu 5.15.0-76-generic #83~20.04.1-Ubuntu SMP Wed Jun 21 20:23:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Terminal name/version

Ubuntu Terminal

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### Affected language servers

clangd

### How to reproduce the issue

1. 进入kernel源码目录，正常编译
make defconfig && make -j32
2. 生成compile_commands.json 
./scripts/clang-tools/gen_compile_commands.py .
3. 打开nvim，进入到某一个.c文件，确认compile_commands.json中已包含该文件
4. 正常进行查看某一个函数的回调，现象如下：
![image](https://github.com/ayamir/nvimdots/assets/22770951/53d0a64e-b115-4285-9819-4081ecbcc346)
最大只支持一个层次显示，无法跳转更深层次的调用函数(vscode是支持的)

### Actual behavior

![image](https://github.com/ayamir/nvimdots/assets/22770951/e34f73c5-95c1-4acc-9bd3-e4c3e3897b14)
如果光标在某一个函数时，窗口不能高亮该函数，很难找这个函数的位置在哪儿，并且这个窗口挡住了调用函数的源代码窗口。
![image](https://github.com/ayamir/nvimdots/assets/22770951/925ce1a6-cd5e-4e84-bd5a-72432503e940)
类似这样，对用户很不友好，既然clangd支持，vscode这个功能支持的很好，我想可以优化一下。

### Expected behavior

下面是vscode的表现：
![image](https://github.com/ayamir/nvimdots/assets/22770951/6ed723c8-af42-4606-b0f2-ec992ca36617)

### Support info

:LspInfo
![image](https://github.com/ayamir/nvimdots/assets/22770951/73172c90-205e-4cda-8bad-1e2ac5dc7387)

:Mason

![image](https://github.com/ayamir/nvimdots/assets/22770951/0f1faaf2-bd09-48f5-ab91-8c9d21609e61)

**Comment by Jint-lzxy** [comment]
Ah I see ur issue. TBH Lspsaga's naming convention is quite counterintuitive, the "expand" command you're looking for is (`toggle_or_req` / `u`):
https://github.com/ayamir/nvimdots/blob/10e2e491402de420c38ebfa654536a2bd6ff1986/lua/modules/configs/completion/lspsaga.lua#L40-L52

Another issue is u need to install a [patched font](https://www.nerdfonts.com/font-downloads) in order to have the icons rendered correctly. The missing icon here is actually a closed-fold (sth like `⌄`), this probably affects ur understanding.

> 如果游標在某一個函式時，視窗不能高亮該函式，很難找這個函式的位置在哪兒，並且這個視窗擋住了呼叫函式的原始碼視窗。

This is an upstream issue (and AFAIK only CallHierarchy is missing curword highlight). You may need to [open a feature request upstream](https://github.com/nvimdev/lspsaga.nvim/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.md&title=).

**Comment by Jint-lzxy** [comment]
https://github.com/nvimdev/lspsaga.nvim/commit/6d779eebd2a9944d3888883532635ae96369691b
